# Generated by Django 3.2.25 on 2025-06-16 17:31

import Profile.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('Preiorety', models.CharField(choices=[('H', 'high'), ('M', 'medium'), ('L', 'low')], default='M', max_length=1)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(default=datetime.date(2025, 6, 23))),
                ('list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.tasklist')),
            ],
            options={
                'ordering': ['Preiorety'],
            },
        ),
        migrations.CreateModel(
            name='CountryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_1', models.ForeignKey(default=models.ForeignKey(default=Profile.models.get_default_country, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country'), on_delete=django.db.models.deletion.CASCADE, related_name='country_1', to='cities_light.country')),
                ('country_2', models.ForeignKey(default=models.ForeignKey(default=Profile.models.get_default_country, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country'), on_delete=django.db.models.deletion.CASCADE, related_name='country_2', to='cities_light.country')),
                ('country_3', models.ForeignKey(default=models.ForeignKey(default=Profile.models.get_default_country, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country'), on_delete=django.db.models.deletion.CASCADE, related_name='country_3', to='cities_light.country')),
                ('country_4', models.ForeignKey(default=models.ForeignKey(default=Profile.models.get_default_country, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country'), on_delete=django.db.models.deletion.CASCADE, related_name='country_4', to='cities_light.country')),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
