# Generated by Django 3.2.25 on 2025-06-26 14:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('Preiorety', models.CharField(choices=[('H', 'high'), ('M', 'medium'), ('L', 'low')], default='M', max_length=1)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(default=datetime.date(2025, 7, 3))),
                ('list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.tasklist')),
            ],
            options={
                'ordering': ['Preiorety'],
            },
        ),
    ]
