# Generated by Django 3.2.25 on 2024-12-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Preiorety',
            field=models.CharField(choices=[('H', 'high'), ('M', 'medium'), ('L', 'low')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
