# Generated by Django 3.2.25 on 2025-06-24 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.date(2025, 7, 1)),
        ),
        migrations.DeleteModel(
            name='CountryList',
        ),
    ]
