# Generated by Django 3.2.25 on 2024-12-22 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20241222_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.TimeField(blank=True, default=datetime.datetime(2024, 12, 23, 17, 42, 53, 990735), null=True),
        ),
    ]
