# Generated by Django 3.2.25 on 2024-12-22 17:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 23, 17, 46, 6, 302282), null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 12, 22, 17, 46, 6, 302294))]),
        ),
    ]
