# Generated by Django 3.2.25 on 2024-12-22 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 23, 17, 49, 7, 138505), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
