# Generated by Django 3.2.25 on 2024-12-27 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0018_auto_20241225_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.date(2025, 1, 3)),
        ),
    ]
