# Generated by Django 3.2.25 on 2025-01-10 11:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('Profile', '0020_auto_20250105_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrylist',
            name='country_1',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='country_1', to='cities_light.country'),
        ),
        migrations.AddField(
            model_name='countrylist',
            name='country_2',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='country_2', to='cities_light.country'),
        ),
        migrations.AddField(
            model_name='countrylist',
            name='country_3',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='country_3', to='cities_light.country'),
        ),
        migrations.AddField(
            model_name='countrylist',
            name='country_4',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='country_4', to='cities_light.country'),
        ),
        migrations.AlterField(
            model_name='countrylist',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.date(2025, 1, 17)),
        ),
    ]
