# Generated by Django 3.2.25 on 2025-06-03 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0021_auto_20250110_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.date(2025, 6, 10)),
        ),
    ]
