# Generated by Django 3.2.25 on 2024-12-05 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', django_countries.fields.CountryField(max_length=2)),
                ('FirstName', models.CharField(blank=True, max_length=100)),
                ('LastName', models.CharField(blank=True, max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
