# Generated by Django 3.2.25 on 2024-12-13 19:58

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Country',
            field=django_countries.fields.CountryField(default='us', max_length=2),
        ),
    ]
