# Generated by Django 3.2.25 on 2024-12-13 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('home', '0003_auto_20241213_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='City',
        ),
        migrations.AddField(
            model_name='profile',
            name='Region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region'),
        ),
    ]
