# Generated by Django 3.2.25 on 2024-12-14 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('home', '0004_auto_20241213_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='SubRegion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.subregion'),
        ),
    ]
