# Generated by Django 3.2.25 on 2024-12-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20241225_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='SubRegion',
        ),
    ]
