# Generated by Django 3.2.25 on 2025-06-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20241227_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='choice_field',
            field=models.CharField(choices=[('yesterday', 'yesterday'), ('last week', 'last week'), ('last mounth', 'last mounth')], default='last week', max_length=20),
        ),
    ]
