# Generated by Django 3.2.25 on 2025-06-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_profile_choice_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='choice_field',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_search',
            field=models.CharField(choices=[('yesterday', 'yesterday'), ('last week', 'last week'), ('last mounth', 'last mounth')], default='yesterday', max_length=20),
        ),
    ]
